[build-system]
requires = [
    "setuptools",
    "setuptools_scm",
    "wheel",
    "numpy",
    "scipy",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "siffpy/core/_version.py"

[project]
name = "siffpy"
dynamic = ["version"]
readme = "README.md"
license = "GPL-3.0-or-later"
description = "A package for reading and analyzing .siff data"
authors = [
    {email = "thornquist@rockefeller.edu"},
    {name = "Stephen Thornquist"},
]

dependencies = [
    "numpy >= 1.15",
    "scipy",
    "ruamel.yaml",
    "matplotlib",
]

[project.optional-dependencies]

all = [
    "napari[all]",
    "holoviews",
    "bokeh",
    "dask",
    "pandas",
    #polars
]
image = ["napari[all]", "dask", "bokeh", "holoviews"]
trac = [
    "pandas",
    #polars,
]