[build-system]
requires = [
    "setuptools",
    "setuptools_scm",
    "wheel",
    "numpy >= 1.15",
    "scipy",
    "ruamel.yaml",
    #"siffreadermodule",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "siffpy/core/_version.py"

[project]
name = "siffpy"
dynamic = ["version"]
readme = "README.md"
description = "A package for reading and analyzing .siff data"
authors = [
    {email = "thornquist@rockefeller.edu"},
    {name = "Stephen Thornquist"},
]

[project.optional-dependencies]
all = ["napari[all]","holoviews", "bokeh", "dask"]
image = ["napari[image]", "dask"]