[tox]
envlist = py{39, 310, 311, 312, 313}-numpy{1,2}-suite2p{src,pypi}

[testenv]
# install pytest in the virtualenv where commands will be executed
deps = 
    pytest
    suite2ppypi: suite2p
    suite2psrc: suite2p @ git+https://github.com/MouseLand/suite2p.git
    numpy1: numpy < 2
    numpy2: numpy >= 2
    # suite2p
    dropbox
commands =
    pytest tests