{% set pyproject = load_file_data('../pyproject.toml', from_recipe_dir=True) %}
{% set project = pyproject.get('project',{}) %}

package:
  name: {{ project.get('name') }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../
  #git_url: https://github.com/maimonlab/siffpy.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv 

requirements:
  build:
    - git
    - python
    - pip
    - numpy
    - wheel
    #- setuptools
    - setuptools>=45
    - setuptools_scm[toml]>=6.2
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - scipy
    - h5py
    - importlib_resources
  run:
    - python
    - numpy
    - scipy
    - h5py
    - importlib_resources

test:
  requires:
    - pytest
  imports:
    - siffpy
    #- siffreadermodule
  # commands:
  #   - pytest tests

about:
  home: https://github.com/maimonlab/siffpy
  summary : {{ project.get('description') }}
  license: GPL3
  license_file: ../LICENSE.md
  doc_url: siffpy.readthedocs.io

extra:
  recipe-maintainers:
    - StephenThornquist
