# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.6.2.dev5+gf52e1c0.d20230117'
__version_tuple__ = version_tuple = (0, 6, 2, 'dev5', 'gf52e1c0.d20230117')
