# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.6.2.dev7+ge826a7d.d20230118'
__version_tuple__ = version_tuple = (0, 6, 2, 'dev7', 'ge826a7d.d20230118')
