# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.6.2.dev9+gc4fc210.d20230126'
__version_tuple__ = version_tuple = (0, 6, 2, 'dev9', 'gc4fc210.d20230126')
