"""
For some reason, on some installs, _version.py is _not_
being generated by setuptools_scm! While I figure out what
the issue is, this is a workaround. Hopefully nobody
will see that this file exists except for me, and then
only briefly.    
"""
import logging

__version__ = version = '0.0.0'
__version_tuple__ = version_tuple = (0, 0, 0)

logging.error(
    """
    The version of siffpy you are using was not built
    correctly, either due to a bug in my implementation,
    an incorrect installation command, or a bug in
    setuptools_scm. Please let me (SCT) know,
    and I'll try to fix it as soon as possible.

    On installation, setuptools_scm should create
    a _version.py file in the `siffpy.core` directly
    that contains the version number. This file is
    automatically generated, and if it's absent,
    then siffpy will default to using `shame.py`
    in `siffpy.corre.utils`.

    Likely everything works correctly, but if you
    encounter any issues... this may be related.
    """
)
